@extends('app')

@section('page-title')
    Learn More
@endsection

@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-offset-1 col-md-10 white-background post-main-column">

                <div class="row">
                    <div class="col-md-4 col-sm-5"> {{--Left column--}}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="background-gray">
                                    <img src="/images/money.png" width="130" height="130" class="center-block">
                                    <h4 class="text-center">Industry Highest Revenue Sharing</h4>
                                    <ul>
                                        <li><p>Connect your Google Adsense account and earn <b>{{100-Config::get('app.ad_weight')}}%</b> of the revenue generated by all your posts, higher than any other revenue sharing site.</p></li>
                                    </ul>
                                </div>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="background-gray">
                                    <img src="/images/trends.png" width="130" height="130" class="center-block">
                                    <h4 class="text-center">Massively Widen the Reach of your Content</h4>
                                    <ul>
                                        <li><p>Posting your content here, you automatically gain the reputation of {{Config::get('app.name')}}.</p></li>
                                        <li><p>You could post on your own personal sit but here, you get to skip the process of finding users to read your content.</p></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="background-gray">
                                    <img src="/images/browser.png" width="130" height="130" class="center-block">
                                    <h4 class="text-center">Increase your Writing Profile</h4>
                                    <ul>
                                        <li><p>Build your writing profile on {{Config::get('app.name')}}.</p></li>
                                        <li><p>Gain validation for your writing by tracking your page views.</p></li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                    </div>

                    <div class="col-md-8 col-sm-7"> {{--Right column--}}

                        @if (Session::has('message'))
                            <div class="alert alert-success" role="alert">{{ Session::get('message') }}</div>
                        @endif

                        @if (Session::has('errors'))
                            <div class="alert alert-danger" role="alert">{{ Session::get('errors')->first('email') }}</div>
                        @endif

                        <h1>Registering for {{Config::get('app.name')}}</h1>

                        <h3>Who We Are Looking For</h3>
                        <p>Anyone can write for {{Config::get('app.name')}}. We recommend that you should</p>
                        <ul>
                            <li><p>Be able to write fluently in English</p></li>
                            <li><p>Keep up with modern trends in news, entertainment, and technology</p></li>
                        </ul>

                        <h3>Content We Are Looking For</h3>
                        <p>We are different from other sites in that we are willing to publish all types of English content.</p>
                        <p>We are looking for original, modern, and interesting content.</p>

                        <p>Specifically, we encourage content that is</p>
                        <ul>
                            <li><p>geared towards our target demographic of people from 16-40 years old</p></li>
                            <li><p>relevant (such as TV shows, movies, music, and large news stories)</p></li>
                        </ul>

                        <h3>How it Works</h3>
                        <p>Once logged in, you will see a button in the top right to post content. Submit content such as images, lists, and articles. We are looking for funny, interesting, and cool content. Check out the <a href="/">frontpage</a> for inspiration.</p>

                        <p>Your first 5 posts will be manually approved by a human. After this, your posts will automatically go live on the website when you post.</p>
                        <p>Reasons for denial include</p>

                        <ul>
                            <li><p>Posting with severe grammatical errors</p></li>
                            <li><p>Spam/inappropriate content</p></li>
                        </ul>

                        <p>As long as your post doesn't fall into the above categories, your post will be approved in less than 12 hours.</p>


                        <h3>Revenue</h3>
                        <p>When users visit your post, Adsense advertisements will displayed on the page. <b>{{100-Config::get('app.ad_weight')}}% of the time, advertisements with your publisher ID will be loaded, allowing you to generate revenue.</b></p>
                        <p>You will be able to keep track your generated revenue through Adsense</p>



                        <p>Once a post is listed, you can start sharing your post with your friends and family. For help gaining exposure to your site, take a look our <a href="exposure-guide">exposure guide</a>.</p>



                    </div>
                </div> {{--End inner row--}}

			</div>
		</div> {{--End outer row--}}

		<div class="row sign-up-row-background">
			<div class="col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">

				<h1 class="white-font">Get Notified</h1>
				<p class="white-font">Public sign-ups are not yet open. Good news is that we'll send you an email once you can sign up.</p>

				{!! Form::open(array('route' => 'sign-up-beta-post', 'class' => 'form')) !!}


					<div class="row">
						<div class="col-sm-6 col-sm-offset-2">
							<div class="form-group">
								{!! Form::text('email', null, array('required', 'class'=>'form-control', 'placeholder'=>'Your email', 'type'=>'email')) !!}
							</div>
						</div>

						<div class="col-sm-2">
							<div class="form-group">
								{!! Form::submit('Submit', array('class'=>'btn btn-success')) !!}
							</div>
						</div>
					</div>

				{!! Form::close() !!}

				<p class="small white-font">Your email address will not be shared with anyone else.</p>

			</div>
		</div>


	</div>
@endsection