@extends('app')

@section('page-title')
    Learn More
@endsection

@section('content')
	<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-offset-1 col-md-10 white-background post-main-column">

                <div class="row"> {{--Session messages row--}}
                    <div class="col-md-8 col-md-offset-2">
                        @if (Session::has('message'))
                            <div class="alert alert-success" role="alert">{{ Session::get('message') }}</div>
                        @endif

                        @if (Session::has('errors'))
                            <div class="alert alert-danger" role="alert">{{ Session::get('errors')->first('email') }}</div>
                        @endif
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <img src="/images/User-Add-256.png" width="130" height="130" style="margin-top: 20px;" class="center-block">
                        <h2 class="text-center">Register</h2>
                        <p>Enter your email below to be notified once registrations have started.</p>
                    </div>

                    <div class="col-sm-4">
                        <img src="/images/Note-Information-256.png" width="130" height="130" style="margin-top: 20px;" class="center-block">
                        <h2 class="text-center">Write Posts</h2>
                        <p>Use our post builder to write about recent events, funny things, opinions, or anything else.</p>
                    </div>

                    <div class="col-sm-4">
                        <img src="/images/Donate-256.png" width="130" height="130" style="margin-top: 20px;" class="center-block">
                        <h2 class="text-center">Earn</h2>
                        <p>We offer the industry's highest revenue sharing. Connect your Google Adsense account and earn <b>{{100-Config::get('app.ad_weight')}}%</b> of the revenue generated by your posts.</p>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-8 col-sm-7 col-md-offset-3">

                        <br>
                        {{--<h1>{{Config::get('app.name')}} Explained</h1>--}}
                    </div>
                </div>

                <div class="row" style="background-color: #ECEFF5; padding: 50px 0px;">
                    <div class="col-md-8 col-sm-10 col-md-offset-2 col-sm-offset-1">

                        <h1>Ready To Get Started?</h1>
                        <p>Public registrations start soon.
                        We'll send you an email once you can register.</p>

                        {!! Form::open(array('route' => 'sign-up-beta-post', 'class' => 'form')) !!}

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-10 col-xs-8">
                                        {!! Form::email('email', null, array('required', 'class'=>'form-control', 'placeholder'=>'Your email', 'type'=>'email')) !!}
                                    </div>
                                    <div class="col-sm-2 col-xs-4">
                                        {!! Form::submit('Submit', array('class'=>'btn btn-success btn-block', 'id' => 'submit-beta-email-form')) !!}
                                    </div>
                                </div>
                            </div>

                        {!! Form::close() !!}

                        <p>Still need convincing? <a href="/how-it-works">Learn More.</a></p>

                    </div>
                </div>

			</div>
		</div> {{--End white background--}}

	</div>
@endsection